# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0002_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
