"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(@j_e+k^8oir4l42i#f-l5)%uuac%3qbynd@a+jna9)8@pv16t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'facebook_api',
    'social_django',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'API.urls'

REGISTRATION_OPEN = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
)

TEMPLATE_CONTEXT_PROCESSORS = \
    (
    # ("django.core.context_processors.request",
     # "social.apps.django_app.context_processors.backends",
     # "social.apps.django_app.context_processors.login_redirect",
     # "studentsdb.context_processors.students_proc",
     # "students.context_processors.groups_processor",
     )

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.facebook.FacebookOAuth2',
)

WSGI_APPLICATION = 'API.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

SOCIAL_AUTH_FACEBOOK_KEY = '132816840603239'
SOCIAL_AUTH_FACEBOOK_SECRET = '91ae669a2520d2270c98f2a874bf1ea0'
ACCESS_TOKEN = '132816840603239|7eNhRtQpLzGkzUJ0-Ebka8758cA'
EXISTING_ACCESS_TOKEN = 'EAAB4y9SatmcBAKSnu4jWO9OFzKvXmmhEUMvPNF9mZBPwzNtlY2sKUIzYXRqZCkJvwWIaESWDGQ1FA0dxEIGD83jgW9EQNAyQ9bIcIxW1mLf5FQv2KPyUSiZCwoLgVbURxhZBR0wMVquQjVJSQZBXkx52wWYPa4R4ZD'

# GET_ACCESS_TOKEN_URL = 'https://graph.facebook.com/oauth/access_token?' \
#                    'client_id={APP_ID}&' \
#                    'client_secret={APP_SECRET}&' \
#                    'grant_type=fb_exchange_token&' \
#                    'fb_exchange_token={EXISTING_ACCESS_TOKEN}'.\
#     format(APP_ID=FACEBOOK_CLIENT_ID,
#            APP_SECRET=FACEBOOK_CLIENT_SECRET,
#            EXISTING_ACCESS_TOKEN='EAACEdEose0cBAOK2Op9lRClMQBeZAAcLiT8ZAnMkbbTcTLUc9nZBCZCTZCzme4uHREfeHZAUcg3CZBGPaEAVYmhjPgcbsVsn9j7ZBcPcuqhPH067aZCF24psqa0ZBjc46NpysCnvnDSKXw2QjeI07ZAAqdqTEV3kXpFzFXfTikiOHec14Gz3YSqV5PZBvuLC3IPDVAYZD'
#            )
#
# ACCESS_TOKEN = 'EAAGQu7mMEr0BAChQL9NAAE9lVIAGyJkT1Jnp4AZBxIa1y12bXKf3hu2wx1B3crv0ZBhEgAsqZBoiPZCpRcS0jF28vnmvoC8yZAS6IuVDAVjiVTAeRLn4zJMGOKYwdiXrIJRKMB6ElREdjmf10u1tpJa0k5bV1YboZD'
#
s = 'https://graph.facebook.com/v2.9/me?' \
    'access_token={ACCESS_TOKEN}' \
    '&debug=all' \
    '&fields=id%2Cname' \
    '&format=json' \
    '&method=get' \
    '&pretty=0' \
    '&suppress_http_code=1'.format(ACCESS_TOKEN=EXISTING_ACCESS_TOKEN)

# RESULT_URL = 'https://graph.facebook.com/v2.9/me?access_token={ACCESS_TOKEN}'.\
#     format(ACCESS_TOKEN=ACCESS_TOKEN)
RESULT_URL = ''

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
